import type { AppRole as Role } from "@/lib/roles";
import {
  LayoutDashboard,
  Users,
  UserCheck,
  GraduationCap,
  BookOpen,
  CalendarCheck,
  ClipboardList,
  DollarSign,
  Library,
  Bus,
  Building2,
  MessageSquare,
  Video,
  BarChart3,
  Settings,
  UserCog,
  School,
  Briefcase,
  FileText,
  Bell,
  Home,
  Bug,
  FlaskConical,
  ShieldAlert,
  ShieldCheck,
} from "lucide-react";

export type NavItem = {
  label: string;
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  children?: NavItem[];
};

export const NAV_CONFIG: Record<Role, NavItem[]> = {
  SUPER_ADMIN: [
    { label: "Dashboard", href: "/super-admin/dashboard", icon: LayoutDashboard },
    { label: "Schools", href: "/super-admin/schools", icon: School },
    { label: "School Admins", href: "/super-admin/school-admins", icon: ShieldCheck },
    { label: "Students", href: "/super-admin/students", icon: GraduationCap },
    { label: "Principals", href: "/super-admin/principals", icon: UserCog },
    { label: "Teachers", href: "/super-admin/teachers", icon: UserCheck },
    { label: "Parents", href: "/super-admin/parents", icon: Home },
    { label: "Accountants", href: "/super-admin/accountants", icon: DollarSign },
    { label: "Librarians", href: "/super-admin/librarians", icon: Library },
    { label: "Transport Managers", href: "/super-admin/transport-managers", icon: Bus },
    { label: "HR Managers", href: "/super-admin/hr-managers", icon: Briefcase },
    { label: "Warden Managers", href: "/super-admin/warden-managers", icon: Building2 },
    { label: "Users", href: "/super-admin/users", icon: Users },
    { label: "Reports", href: "/super-admin/reports", icon: BarChart3 },
    { label: "Audit & Security", href: "/super-admin/audit", icon: ShieldAlert },
    { label: "Bug Board", href: "/super-admin/bugs", icon: Bug },
    { label: "Tests", href: "/super-admin/tests", icon: FlaskConical },
    { label: "Settings", href: "/super-admin/settings", icon: Settings },
  ],
  SCHOOL_ADMIN: [
    { label: "Dashboard", href: "/school-admin/dashboard", icon: LayoutDashboard },
    { label: "Students", href: "/school-admin/students", icon: GraduationCap },
    { label: "Parents", href: "/school-admin/parents", icon: Home },
    { label: "Teachers", href: "/school-admin/teachers", icon: UserCheck },
    { label: "Staff", href: "/school-admin/staff", icon: Briefcase },
    { label: "Classes", href: "/school-admin/classes", icon: BookOpen },
    { label: "Subjects", href: "/school-admin/subjects", icon: BookOpen },
    { label: "Timetable", href: "/school-admin/timetable", icon: CalendarCheck },
    { label: "Attendance", href: "/school-admin/attendance", icon: ClipboardList },
    { label: "Exams", href: "/school-admin/exams", icon: FileText },
    { label: "Fees", href: "/school-admin/fees", icon: DollarSign },
    { label: "Reports", href: "/school-admin/reports", icon: BarChart3 },
    { label: "Bug Board", href: "/school-admin/bugs", icon: Bug },
    { label: "Settings", href: "/school-admin/settings", icon: Settings },
  ],
  PRINCIPAL: [
    { label: "Dashboard", href: "/principal/dashboard", icon: LayoutDashboard },
    { label: "Students", href: "/principal/students", icon: GraduationCap },
    { label: "Teachers", href: "/principal/teachers", icon: UserCheck },
    { label: "Timetable", href: "/principal/timetable", icon: CalendarCheck },
    { label: "Attendance", href: "/principal/attendance", icon: ClipboardList },
    { label: "Exams", href: "/principal/exams", icon: FileText },
    { label: "Leave Requests", href: "/principal/leaves", icon: CalendarCheck },
    { label: "Announcements", href: "/principal/announcements", icon: Bell },
    { label: "Reports", href: "/principal/reports", icon: BarChart3 },
    { label: "Bug Board", href: "/principal/bugs", icon: Bug },
  ],
  TEACHER: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard },
    { label: "My Classes", href: "/teacher/classes", icon: BookOpen },
    { label: "Timetable", href: "/teacher/timetable", icon: CalendarCheck },
    { label: "Attendance", href: "/teacher/attendance", icon: ClipboardList },
    { label: "Homework", href: "/teacher/homework", icon: FileText },
    { label: "Exams", href: "/teacher/exams", icon: GraduationCap },
    { label: "Fees", href: "/teacher/fees", icon: DollarSign },
    { label: "LMS", href: "/teacher/lms", icon: Video },
    { label: "Leave", href: "/teacher/leave", icon: CalendarCheck },
    { label: "Communication", href: "/teacher/communication", icon: MessageSquare },
  ],
  STUDENT: [
    { label: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard },
    { label: "Timetable", href: "/student/timetable", icon: CalendarCheck },
    { label: "Attendance", href: "/student/attendance", icon: ClipboardList },
    { label: "Homework", href: "/student/homework", icon: FileText },
    { label: "Exams & Results", href: "/student/results", icon: GraduationCap },
    { label: "Fees", href: "/student/fees", icon: DollarSign },
    { label: "Library", href: "/student/library", icon: Library },
    { label: "LMS", href: "/student/lms", icon: Video },
    { label: "Leave", href: "/student/leave", icon: CalendarCheck },
  ],
  PARENT: [
    { label: "Dashboard", href: "/parent/dashboard", icon: Home },
    { label: "My Child", href: "/parent/child", icon: GraduationCap },
    { label: "Attendance", href: "/parent/attendance", icon: ClipboardList },
    { label: "Results", href: "/parent/results", icon: FileText },
    { label: "Fees", href: "/parent/fees", icon: DollarSign },
    { label: "Homework", href: "/parent/homework", icon: BookOpen },
    { label: "Leave Application", href: "/parent/leave", icon: CalendarCheck },
    { label: "Communication", href: "/parent/communication", icon: MessageSquare },
  ],
  ACCOUNTANT: [
    { label: "Dashboard", href: "/accountant/dashboard", icon: LayoutDashboard },
    { label: "Fee Collection", href: "/accountant/fees/collect", icon: DollarSign },
    { label: "Fee Structures", href: "/accountant/fees/structures", icon: DollarSign },
    { label: "Receipts", href: "/accountant/receipts", icon: FileText },
    { label: "Scholarships", href: "/accountant/scholarships", icon: GraduationCap },
    { label: "Expenses", href: "/accountant/expenses", icon: Briefcase },
    { label: "Payroll", href: "/accountant/payroll", icon: Users },
    { label: "Reports", href: "/accountant/reports", icon: BarChart3 },
  ],
  LIBRARIAN: [
    { label: "Dashboard", href: "/librarian/dashboard", icon: LayoutDashboard },
    { label: "Books", href: "/librarian/books", icon: Library },
    { label: "Issue Book", href: "/librarian/issue", icon: BookOpen },
    { label: "Returns", href: "/librarian/returns", icon: BookOpen },
    { label: "Fines", href: "/librarian/fines", icon: DollarSign },
    { label: "Reports", href: "/librarian/reports", icon: BarChart3 },
  ],
  TRANSPORT_MANAGER: [
    { label: "Dashboard", href: "/transport/dashboard", icon: LayoutDashboard },
    { label: "Routes", href: "/transport/routes", icon: Bus },
    { label: "Vehicles", href: "/transport/vehicles", icon: Bus },
    { label: "Students", href: "/transport/students", icon: Users },
    { label: "Fees", href: "/transport/fees", icon: DollarSign },
  ],
  HR_MANAGER: [
    { label: "Dashboard", href: "/hr/dashboard", icon: LayoutDashboard },
    { label: "Employees", href: "/hr/employees", icon: Users },
    { label: "Attendance", href: "/hr/attendance", icon: ClipboardList },
    { label: "Leave Requests", href: "/hr/leaves", icon: CalendarCheck },
    { label: "Payroll", href: "/hr/payroll", icon: DollarSign },
    { label: "Recruitment", href: "/hr/recruitment", icon: Briefcase },
    { label: "Performance", href: "/hr/performance", icon: BarChart3 },
  ],
  WARDEN_MANAGER: [
    { label: "Dashboard", href: "/warden/dashboard", icon: LayoutDashboard },
    { label: "Rooms", href: "/warden/rooms", icon: Building2 },
    { label: "Allocations", href: "/warden/allocations", icon: Users },
    { label: "Attendance", href: "/warden/attendance", icon: ClipboardList },
    { label: "Visitors", href: "/warden/visitors", icon: UserCog },
    { label: "Fees", href: "/warden/fees", icon: DollarSign },
  ],
  MESS_MANAGER: [
    { label: "Dashboard", href: "/mess/dashboard", icon: LayoutDashboard },
    { label: "Menu", href: "/mess/menu", icon: BookOpen },
    { label: "Attendance", href: "/mess/attendance", icon: ClipboardList },
    { label: "Reports", href: "/mess/reports", icon: BarChart3 },
  ],
};
